#!/bin/bash

find * -type d -print | tr " " "\n" | sed "s:.*:#include \"&/&.h\":"
echo -e "\n#define CPUS_CMDLINE_HELP \\"
find * -type d -print | tr " " "\n" | sed "s:.*:&_CMDLINE_HELP \\\\:"
#echo -e "{ wxCMD_LINE_SWITCH, wxT(\"c\"), wxT(\"cpus\"), wxT(\"CPUS!\") },"
echo ""
